# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binarySearch <- function(arr, l, r, x) {
    .Call('_medLDM_binarySearch', PACKAGE = 'medLDM', arr, l, r, x)
}

is_inCpp <- function(x, y) {
    .Call('_medLDM_is_inCpp', PACKAGE = 'medLDM', x, y)
}

